### ISSUE TITLE
can not parse the  miniSEED256 format of payload

### ISSUE THREAD

**Issue by qiufujian** [iris-edu/slarchive#3]
When receiving seedlink dara for format of miniseed256, the slarchive throws an error: "sl_collect: non-miniSEED packet received!?! Terminating."

**Comment by chad-earthscope** [comment]
This is because the SeedLink specification only officially allows 512-byte miniSEED records.  From https://www.seiscomp.de/doc/apps/seedlink.html:

> When handshaking is completed, a stream of SeedLink “packets” consisting of a 8-byte SeedLink header (containing the sequence number) followed by a 512-byte miniSEED record, is sent to the client.

The next version of slarchive will support other miniSEED records lengths despite this limitation in the specification.

**Comment by qiufujian** [comment]
OK, thank you for your prompt reply
