### ISSUE TITLE
Can slarchive tool to be used to release the ring buffer, whenever it imminent goes to reach the max-size close to 9Gb?

### ISSUE THREAD

**Issue by cajaraujo** [iris-edu/slarchive#4]
Hie all,
i've a doubt because didn't see the information on slarchive manual. Can slarchive tool to be used to release the ring buffer, whenever it imminent goes to reach the max-size close to 9Gb? Otherwise, is there other tool to do that?

Regards, Cleir

**Comment by chad-earthscope** [comment]
Hello @cajaraujo.  I do not fully understand what you are asking.  slarchive does have have a buffer, instead it writes received miniSEED records immediately to the file system.

Is the buffer you are referring to a SeedLink server perhaps?  If so, there is nothing a SeedLink client can do to effect the data within a server.

Can you add more detail to your question?

**Comment by cajaraujo** [comment]
Hie Chad. Thank you for your response. The archive tool proposal is very well explained and you-re right! My main doubt is: there is a way to escape from ring buffer limitation, nowadays at around 9 Gb?

Thank you, again!

**Comment by cajaraujo** [comment]
Sorry @chad-earthscope, my bad. I just saw an option inside ringserver enough to treat my scenario! For anyway, thank you for attention and cordiality! Please consider it up closed!

**Comment by chad-earthscope** [comment]
Glad you figured something out!
